### ISSUE TITLE
Compile once and run more time

### ISSUE THREAD

**Issue by muhammadhemdan** [suhaasr/15769_final_project#2]
Hi,
I need to run HDRPlus to process images in run time, so I need to compile it once not every time I give him new images. I knew two ways to do that:
1. using compile_jit() once, then call realize() more time. But how can I do that in this project?
2. using compile_to_file() but I don't know also how to do that with this project?

thanks,

**Comment by suhaasr** [comment]
Please direct questions and issues to https://github.com/timothybrooks/hdr-plus . That version is still being (lightly) maintained, though not by me or Tim ourselves.
